name: Validate HTML
on:
  push:
jobs:
  html-check:
    name: Validate HTML
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v4
      - name: Use NodeJS 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install and Build ğŸ› ï¸
        run:  |
          npm install
          npm run build
      - name: Run HTML5 Validator âš™ï¸
        uses: Cyb3r-Jak3/html5validator-action@master
        with:
          root: dist/
          format: text
          log_level: WARNING
          css: true
        continue-on-error: true
      - name: Upload Artifact ğŸ“„
        uses: actions/upload-artifact@v4
        with:
          name: log
          path: log.log
